name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          system-features = benchmark big-parallel kvm nixos-test gccarch-skylake benchmark big-parallel kvm nixos-test
          extra-access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          extra-experimental-features = nix-command flakes
          extra-substituters = https://cache.nx.section.me/nx
          extra-trusted-substituters = https://cache.nx.section.me/nx
          extra-trusted-public-keys = nx:ctJWp8Nkzf4gXc9ZUQ81dRc7BbMlUzAEerI0nod0gPw=
    - run: nix build .#nixosConfigurations.exampleIso.config.system.build.isoImage
    - run: nix flake check
